# R 語言的五十道練習

> 資料結構：因素向量、矩陣與陣列

[數據交點](https://www.datainpoint.com/) | 郭耀仁 <yaojenkuo@datainpoint.com>

## 練習題指引

- 第一個程式碼儲存格會將可能用得到的套件以及單元測試 `testthat` 載入。
- 如果練習題需要載入檔案，檔案與練習題存放在同個資料夾中，意即我們可以指定工作目錄來載入。
- 練習題已經定義好函數的名稱以及參數名稱，我們只需要寫作主體。
- 函數名稱下面幾行的註解部分是在描述測試如何進行。
- 觀察函數名稱下面幾行的註解部分能夠暸解輸入以及預期輸出之間的關係，幫助我們更暸解題目。
- 在 `### BEGIN SOLUTION` 與 `### END SOLUTION` 這兩個單行註解之間撰寫函數的主體。
- 可以先在 RStudio 寫出跟預期結果相同的程式後再複製貼上到練習題。
- 執行測試的方式為點選上方選單的 Kernel -> Restart & Run All -> Restart and Run All Cells。
- 可以每寫一題就執行測試，也可以全部寫完再執行測試。
- 練習題閒置超過 10 分鐘會自動斷線，這時只要重新點選練習題連結即可重新啟動。

In [1]:
library("testthat")

## 自行定義函數 `create_speed_factor` 以因素向量回傳速度資訊。

- 預期輸入：無。
- 預期輸出：一個長度為 5 的因素向量。

```
[1] slow   slow   medium fast   fast  
Levels: fast medium slow
```

In [2]:
create_speed_factor <- function() {
    # speed_factor <- create_speed_factor()
    # speed_factor
    # [1] slow   slow   medium fast   fast  
    # Levels: fast medium slow
    ### BEGIN SOLUTION
    out <- factor(c("slow", "slow", "medium", "fast", "fast"))
    return(out)
    ### END SOLUTION
}

## 自行定義函數 `create_speed_factor_with_order` 以「有序」的因素向量回傳速度資訊。

- 預期輸入：無。
- 預期輸出：一個長度為 5 的因素向量。

```
[1] slow   slow   medium fast   fast  
Levels: slow < medium < fast
```

In [3]:
create_speed_factor_with_order <- function() {
    # speed_factor_with_order <- create_speed_factor_with_order()
    # speed_factor_with_order
    # [1] slow   slow   medium fast   fast  
    # Levels: slow < medium < fast
    ### BEGIN SOLUTION
    out <- factor(c("slow", "slow", "medium", "fast", "fast"), levels = c("slow", "medium", "fast"), order = TRUE)
    return(out)
    ### END SOLUTION
}

## 自行定義函數 `create_a_square_matrix(n, x)` 回傳一個方塊矩陣，即列數（`n`）與欄數（`n`）相同的矩陣，矩陣中的元素都相同為 `x`。

- 預期輸入：兩個整數。
- 預期輸出：一個外型 `n x n` 的矩陣。

In [4]:
create_a_square_matrix <- function(n, x) {
    # create_a_square_matrix(n = 3, x = 1)
    #      [,1] [,2] [,3]
    # [1,]    1    1    1
    # [2,]    1    1    1
    # [3,]    1    1    1
    # create_a_square_matrix(n = 2, x = 5)
    #      [,1] [,2]
    # [1,]    5    5
    # [2,]    5    5
    ### BEGIN SOLUTION
    elems <- rep(x, times = n**2)
    out <- matrix(elems, nrow = n, ncol = n)
    return(out)
    ### END SOLUTION
}

## 自行定義函數 `create_square_matrices(m, n, x)` 以陣列資料結構回傳 `m` 個方塊矩陣，矩陣中的元素都相同為 `x`。

- 預期輸入：三個整數。
- 預期輸出：一個由 `m` 個 `n x n` 方塊矩陣組成的陣列。

In [5]:
create_square_matrices <- function(m, n, x) {
    # create_square_matrices(m = 1, n = 2, x = 3)
    # , , 1

    #      [,1] [,2]
    # [1,]    3    3
    # [2,]    3    3
    # create_square_matrices(m = 3, n = 2, x = 1)
    # , , 1

    #      [,1] [,2]
    # [1,]    1    1
    # [2,]    1    1

    # , , 2

    #      [,1] [,2]
    # [1,]    1    1
    # [2,]    1    1

    # , , 3

    #      [,1] [,2]
    # [1,]    1    1
    # [2,]    1    1
    ### BEGIN SOLUTION
    elems <- rep(x, times = m*n**2)
    out <- array(elems, dim = c(n, n, m))
    return(out)
    ### END SOLUTION
}

## 自行定義函數 `find_the_center_of_square_matrix` 能夠回傳方塊矩陣中心的數字，僅考慮 `n` 為奇數的情況即可。

- 預期輸入：一個 `n x n` 的方塊矩陣，`n` 為奇數。
- 預期輸出：一個數值。

In [6]:
find_the_center_of_square_matrix <- function(mat) {
    # square_matrix <- matrix(1:9, nrow = 3, ncol = 3)
    # find_the_center_of_square_matrix(square_matrix)
    # [1] 5
    # square_matrix <- matrix(1:25, nrow = 5, ncol = 5)
    # find_the_center_of_square_matrix(square_matrix)
    # [1] 13
    ### BEGIN SOLUTION
    n <- nrow(mat)
    center_index <- n %/% 2 + 1
    out <- mat[center_index, center_index]
    return(out)
    ### END SOLUTION
}

## 執行測試

Kernel -> Restart & Run All. -> Restart and Run All Cells. 

In [7]:
test_create_speed_factor <- tryCatch({
    test_that("test_create_speed_factor", {
        expect_s3_class(create_speed_factor(), "factor")
        expect_length(create_speed_factor(), 5)
        expect_length(levels(create_speed_factor()), 3)
    })
    }, error = function(e) {
        FALSE
})
test_create_speed_factor_with_order <- tryCatch({
    test_that("test_create_speed_factor_with_order", {
        expect_s3_class(create_speed_factor_with_order(), "factor")
        expect_length(create_speed_factor_with_order(), 5)
        expect_length(levels(create_speed_factor_with_order()), 3)
        expect_true(create_speed_factor_with_order()[1] < create_speed_factor_with_order()[3])
    })
    }, error = function(e) {
        FALSE
})
test_create_a_square_matrix <- tryCatch({
    test_that("test_create_a_square_matrix", {
        expect_true(is.matrix(create_a_square_matrix(n = 3, x = 1)))
        expect_equal(dim(create_a_square_matrix(n = 3, x = 1)), c(3, 3))
        expect_equal(sum(create_a_square_matrix(n = 3, x = 1)), 9)
        expect_true(is.matrix(create_a_square_matrix(n = 2, x = 5)))
        expect_equal(dim(create_a_square_matrix(n = 2, x = 5)), c(2, 2))
        expect_equal(sum(create_a_square_matrix(n = 2, x = 5)), 20)
    })
    }, error = function(e) {
        FALSE
})
test_create_square_matrices <- tryCatch({
    test_that("test_create_square_matrices", {
        expect_true(is.array(create_square_matrices(m = 1, n = 2, x = 3)))
        expect_equal(dim(create_square_matrices(m = 1, n = 2, x = 3)), c(2, 2, 1))
        expect_equal(sum(create_square_matrices(m = 1, n = 2, x = 3)), 12)
        expect_true(is.array(create_square_matrices(m = 3, n = 2, x = 1)))
        expect_equal(dim(create_square_matrices(m = 3, n = 2, x = 1)), c(2, 2, 3))
        expect_equal(sum(create_square_matrices(m = 3, n = 2, x = 1)), 12)
    })
    }, error = function(e) {
        FALSE
})
test_find_the_center_of_square_matrix <- tryCatch({
    test_that("test_find_the_center_of_square_matrix", {
        expect_equal(find_the_center_of_square_matrix(matrix(1:9, nrow = 3, ncol = 3)), 5)
        expect_equal(find_the_center_of_square_matrix(matrix(1:25, nrow = 5, ncol = 5)), 13)

    })
    }, error = function(e) {
        FALSE
})

all_tests <- c(test_create_speed_factor,
               test_create_speed_factor_with_order,
               test_create_a_square_matrix,
               test_create_square_matrices,
               test_find_the_center_of_square_matrix
              )
passed_tests <- sum(all_tests)

Test passed 🥇
Test passed 🥳
Test passed 😸
Test passed 😀
Test passed 🥇


In [8]:
sprintf("在 %s 題練習中，您總共答對了 %s 題。", length(all_tests), passed_tests)

[1] "在 5 題練習中，您總共答對了 5 題。"